<?xml version="1.0" encoding="utf-8"?><Database Name="Delivery_Mev" Class="DbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=Delivery_Mev;Integrated Security=True" SettingsObjectName="delivery.Properties.Settings" SettingsPropertyName="Delivery_MevConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Provinces" Member="Provinces">
    <Type Name="Province">
      <Column Name="ID_Province" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProvinceName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Exist" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Cities" Member="Cities">
    <Type Name="City">
      <Column Name="ID_City" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CityName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PriceMen" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="PriceWomen" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="ID_Province" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Days" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Exist" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>